 # PostgreSQL. Versions 7.4 and 8.x are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: uptosnuff_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: uptosnuff_test
  pool: 5
  username:
  password:

